using System;

namespace Outbridge.PyLite.Runtime.Values
{
    // unicodedata's East Asian Width and canonical combining class, over tables generated by
    // tools/Outbridge.PyLite.UnicodeGen (PyUnicodeProps.Tables.g.cs). An unlisted code point is N / 0.
    internal static partial class PyUnicodeProps
    {
        private static readonly string[] WidthCodes = { "N", "A", "H", "W", "F", "Na" };

        internal static string EastAsianWidth(int cp)
        {
            int i = Array.BinarySearch(EawStart, cp);
            if (i < 0)
                i = ~i - 1;   // the run that started before cp; EawStart[0] is 0, so i >= 0
            return WidthCodes[EawValue[i]];
        }

        internal static int Combining(int cp)
        {
            int i = RangeIndex(CccStart, CccEnd, cp);
            return i < 0 ? 0 : CccValue[i];
        }

        // True when cp can be the SECOND element of a canonical composition, i.e. when splitting a string
        // right before cp could lose an NFC composition. Combining marks (ccc > 0) are not listed: a caller
        // splitting a string must reject those on their own. Hangul V/T compose algorithmically.
        internal static bool IsCompositionSecond(int cp)
        {
            if ((cp >= 0x1161 && cp <= 0x1175) || (cp >= 0x11A8 && cp <= 0x11C2))
                return true;
            System.Collections.Generic.HashSet<int> seconds = _compositionSeconds;
            if (seconds == null)
            {
                seconds = BuildCompositionSeconds();
                _compositionSeconds = seconds;
            }
            return seconds.Contains(cp);
        }

        private static volatile System.Collections.Generic.HashSet<int> _compositionSeconds;

        // The starters that end a two-character canonical decomposition (71 of them in Unicode 16.0:
        // Indic vowel signs, Tibetan and Balinese pieces). Built once from the decomposition table.
        private static System.Collections.Generic.HashSet<int> BuildCompositionSeconds()
        {
            var seconds = new System.Collections.Generic.HashSet<int>();
            for (int i = 0; i < DecompCp.Length; i++)
            {
                int start = DecompOffset[i];
                int end = DecompOffset[i + 1];
                if (start >= end || DecompText[start] == '<')
                    continue;                       // a compatibility mapping never recomposes
                int sp = start;
                while (sp < end && DecompText[sp] != ' ')
                    sp++;
                if (sp >= end)
                    continue;                       // a singleton decomposition
                int second = 0;
                int j = sp + 1;
                for (; j < end; j++)
                {
                    int d = HexDigit(DecompText[j]);
                    if (d < 0)
                        break;
                    second = second * 16 + d;
                }
                if (j == end && Combining(second) == 0)
                    seconds.Add(second);            // j < end means a third field: not a pair
            }
            return seconds;
        }

        private static int HexDigit(char c)
        {
            if (c >= '0' && c <= '9')
                return c - '0';
            if (c >= 'A' && c <= 'F')
                return c - 'A' + 10;
            if (c >= 'a' && c <= 'f')
                return c - 'a' + 10;
            return -1;
        }

        // The bidi class code, "" for an unassigned code point (CPython answers the same).
        internal static string Bidirectional(int cp)
        {
            int i = Array.BinarySearch(BidiStart, cp);
            if (i < 0)
                i = ~i - 1;
            return BidiCodes[BidiValue[i]];
        }

        internal static bool Mirrored(int cp)
        {
            return RangeIndex(MirrorStart, MirrorEnd, cp) >= 0;
        }

        // The UnicodeData decomposition field verbatim ("0041 0300", "<fraction> 0031 2044 0032"), "" if none.
        internal static string Decomposition(int cp)
        {
            int i = Array.BinarySearch(DecompCp, cp);
            if (i < 0)
                return "";
            return DecompText.Substring(DecompOffset[i], DecompOffset[i + 1] - DecompOffset[i]);
        }

        private static int RangeIndex(int[] starts, int[] ends, int cp)
        {
            int lo = 0, hi = starts.Length - 1;
            while (lo <= hi)
            {
                int mid = (lo + hi) / 2;
                if (cp < starts[mid])
                    hi = mid - 1;
                else if (cp > ends[mid])
                    lo = mid + 1;
                else
                    return mid;
            }
            return -1;
        }
    }
}
